#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build XCArchive

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        description: 'The version number of the framework embedded in the XCArchives.'
        type: string
        required: true

jobs:
  build-xcarchive:
    uses: StanfordBDHG/.github/.github/workflows/archive.yml@feat/enable-interop-archiving
    strategy:
      matrix:
        include:
          - configuration: Release
            cxxInterop: false
          - configuration: Debug  # Only able to build with enabled C++ interop in Debug configuration
            cxxInterop: true
    with:
      workspaceFile: RKWorkspace.xcworkspace
      xcArchiveName: ResearchKit
      scheme: ResearchKit
      version: ${{ inputs.version }}
      configuration: ${{ matrix.configuration }}
      cxxInterop: ${{ matrix.cxxInterop }}
      runsonlabels: '["macOS", "self-hosted"]'
