#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build XCArchive

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        description: 'The version number of the framework embedded in the XCArchives.'
        type: string
        required: true

jobs:
  build-xcarchive:
    uses: StanfordBDHG/.github/.github/workflows/archive.yml@feat/enable-interop-archiving
    with:
      workspaceFile: RKWorkspace.xcworkspace
      xcArchiveName: ResearchKit
      scheme: ResearchKit
      version: ${{ inputs.version }}
      configuration: Release
      runsonlabels: '["macOS", "self-hosted"]'

  build-xcarchive-cxx-interop:
    uses: StanfordBDHG/.github/.github/workflows/archive.yml@feat/enable-interop-archiving
    with:
      workspaceFile: RKWorkspace.xcworkspace
      xcArchiveName: ResearchKit
      scheme: ResearchKit
      version: ${{ inputs.version }}
      configuration: Release
      cxxInterop: true
      runsonlabels: '["macOS", "self-hosted"]'
